stages:          
  - test
  - deploy
  - destroy


variables:
  TF_VAR_vsphere_password: "$vsphere_password"
  TF_VAR_working_directory: "$working_directory"


before_script:
  - cd ${working_directory}
  - sudo yum update -y  
  - sudo yum install -y curl unzip 
  - curl -fsSL https://releases.hashicorp.com/terraform/1.1.0/terraform_1.1.0_linux_amd64.zip -o ${working_directory}/terraform.zip
  - sudo unzip -o ${working_directory}/terraform.zip -d /usr/local/bin/
  - sudo chmod +x /usr/local/bin/terraform
  - terraform init 

  

test-job:   
  stage: test    
  script:
    - terraform --version
    - terraform validate
    - terraform plan -out=check.tfplan "terraform.tfstate"
  artifacts:
    paths:
      - "check.tfplan"


deploy-job:   
  stage: deploy    
  script:
    - terraform apply -auto-approve "check.tfplan" 
    - terraform output -json master_ip_addresses > "${working_directory}/master_ip_addresses.json"
    - terraform output -json worker_ip_addresses > "${working_directory}/worker_ip_addresses.json"
    - ls -la ${working_directory}
  artifacts:
    paths:
      - "terraform.tfstate"
      - "master_ip_addresses.json"
      - "worker_ip_addresses.json"
    


destroy-job:  
  stage: destroy
  script:
    - terraform destroy -auto-approve 
  when: manual  



