stages:          
  - test
  - deploy
  - destroy


variables:
  TF_VAR_vsphere_password: "$vsphere_password"
  TF_VAR_working_directory: "$working_directory"


before_script:
  - cd ${working_directory}
  - ls -la ${working_directory}
  - sudo yum update -y  
  - sudo yum install -y curl unzip 
  - curl -fsSL https://releases.hashicorp.com/terraform/1.1.0/terraform_1.1.0_linux_amd64.zip -o ${working_directory}/terraform.zip
  - sudo unzip -o ${working_directory}/terraform.zip -d /usr/local/bin/
  - sudo chmod +x /usr/local/bin/terraform
  - export AWS_ACCESS_KEY_ID="AKIATPG5KZCGRC2AXBR5"
  - export AWS_SECRET_ACCESS_KEY="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"
  - export AWS_REGION="eu-west-1"
  - terraform --version
  - terraform init -migrate-state

cache:
  paths:
    - "$working_directory/.terraform"
  

test-job:   
  stage: test    
  script:
    - terraform validate
    - terraform plan -out=check.tfplan 
  artifacts:
    paths:
      - "check.tfplan"


deploy-job:   
  stage: deploy    
  script:
    - terraform apply -auto-approve 
  artifacts:
    paths:
      - "terraform.tfstate"


destroy-job:  
  stage: destroy
  script:
    - terraform destroy -auto-approve 
  when: manual  



