stages:
  - test
  - deploy
  - destroy

variables:
  TF_VAR_vsphere_password: "$vsphere_password"

before_script:
  - sudo yum update -y
  - sudo yum install -y curl unzip
  - curl -fsSL https://releases.hashicorp.com/terraform/1.1.0/terraform_1.1.0_linux_amd64.zip -o ./terraform.zip
  - sudo unzip -o ./terraform.zip -d /usr/local/bin/
  - sudo chmod +x /usr/local/bin/terraform
  - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  - export AWS_REGION=$AWS_REGION
  - terraform --version
  - terraform init -migrate-state

test-job:
  stage: test
  script:
    - terraform validate
    - terraform plan -out=check.tfplan
  artifacts:
    paths:
      - "check.tfplan"
  when: manual

deploy-job:
  stage: deploy
  script:
    - terraform apply -auto-approve
  when: manual

destroy-job:
  stage: destroy
  script:
    - terraform destroy -auto-approve
